### ISSUE TITLE
add `c.Locals(fiber.HeaderXRequestID, rid)` to get request id in handler

### ISSUE THREAD

**Issue by trim21** [gofiber/requestid#1]

**Comment by Fenny** [comment]
https://github.com/gofiber/requestid/pull/3, https://github.com/gofiber/requestid/pull/2

Since the ID is set to the `Response` header, you cannot access it with the `ctx.Get` method, since that only peeks the request headers. Therefor I added a helper function inside this middleware called `Get` to retrieve the ID from the response header.

https://github.com/gofiber/requestid/blob/master/main.go#L54
```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/requestid"
)

func main() {
	app := fiber.New()

	app.Use(requestid.New())

	app.Get("/", func(c *fiber.Ctx) {
		c.Send(requestid.Get(c))
	})
	
	app.Listen(3000)
}

```

Sorry for the late reply, I didn't had notifications enabled for this repo 🎧 
It's available in [`v0.0.3`](https://github.com/gofiber/requestid/releases/tag/v0.0.3) I hope this fixed your problem ❤️
